from toontown.coghq.SpecImports import *
GlobalEntities = {1000: {'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500,
        'modelFilename': 'phase_11/models/lawbotHQ/LB_Zone04a',
        'wantDoors': 1},
 1001: {'type': 'editMgr',
        'name': 'EditMgr',
        'parentEntId': 0,
        'insertEntity': None,
        'removeEntity': None,
        'requestNewEntity': None,
        'requestSave': None},
 0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
 10055: {'type': 'collisionSolid',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'length': 20.0,
         'radius': 15.0,
         'showSolid': 0,
         'solidType': 'tube'},
 10058: {'type': 'collisionSolid',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10008,
         'pos': Point3(29.3404, 25.876, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(1, 1, 1),
         'length': 6.0,
         'radius': 3.0,
         'showSolid': 0,
         'solidType': 'tube'},
 10059: {'type': 'collisionSolid',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 10008,
         'pos': Point3(-13.34, 25.88, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(1, 1, 1),
         'length': 6.0,
         'radius': 3.0,
         'showSolid': 0,
         'solidType': 'tube'},
 10001: {'type': 'model',
         'name': 'middlePillar',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(4.40185, 4.40185, 4.40185),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_pillar.bam'},
 10002: {'type': 'model',
         'name': 'leftCouch',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(-12.4308, 0, 0),
         'hpr': Vec3(270, 0, 0),
         'scale': Vec3(2, 2, 2),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_couchA.bam'},
 10003: {'type': 'model',
         'name': 'rightCouch',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(12.43, 0, 0),
         'hpr': Point3(90, 0, 0),
         'scale': Vec3(2, 2, 2),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_couchA.bam'},
 10004: {'type': 'model',
         'name': 'frontChair',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(0, -13, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(2, 2, 2),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_chairA.bam'},
 10005: {'type': 'model',
         'name': 'backChair',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(0, 13, 0),
         'hpr': Point3(180, 0, 0),
         'scale': Point3(2, 2, 2),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_chairA.bam'},
 10006: {'type': 'model',
         'name': 'frontlamp',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(-10, -14, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(2, 2, 2),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_torch_lampB.bam'},
 10007: {'type': 'model',
         'name': 'backLamp',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(10, 14, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(2, 2, 2),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_torch_lampB.bam'},
 10009: {'type': 'model',
         'name': 'movingShelf',
         'comment': '',
         'parentEntId': 10014,
         'pos': Point3(0.1, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 0.7, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10012: {'type': 'model',
         'name': 'leftShelf',
         'comment': '',
         'parentEntId': 10014,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10013: {'type': 'model',
         'name': 'rightShelf',
         'comment': '',
         'parentEntId': 10014,
         'pos': Point3(15.8, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10015: {'type': 'model',
         'name': 'copy of leftShelf',
         'comment': '',
         'parentEntId': 10016,
         'pos': Point3(0, 0, 0),
         'hpr': Point3(180, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10017: {'type': 'model',
         'name': 'copy of leftShelf (2)',
         'comment': '',
         'parentEntId': 10016,
         'pos': Point3(8.7, 0, 0),
         'hpr': Point3(180, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10018: {'type': 'model',
         'name': 'copy of leftShelf (3)',
         'comment': '',
         'parentEntId': 10016,
         'pos': Point3(17.4, 0, 0),
         'hpr': Point3(180, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10019: {'type': 'model',
         'name': 'copy of leftShelf',
         'comment': '',
         'parentEntId': 10014,
         'pos': Point3(-8.7, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10020: {'type': 'model',
         'name': 'copy of rightShelf',
         'comment': '',
         'parentEntId': 10014,
         'pos': Point3(24.5, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10023: {'type': 'model',
         'name': 'copy of rightShelf (2)',
         'comment': '',
         'parentEntId': 10021,
         'pos': Point3(-10.66, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10024: {'type': 'model',
         'name': 'copy of rightShelf (3)',
         'comment': '',
         'parentEntId': 10021,
         'pos': Point3(-1.97, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10025: {'type': 'model',
         'name': 'copy of rightShelf (4)',
         'comment': '',
         'parentEntId': 10021,
         'pos': Point3(6.65, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10026: {'type': 'model',
         'name': 'copy of rightShelf (3)',
         'comment': '',
         'parentEntId': 10022,
         'pos': Point3(0, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10027: {'type': 'model',
         'name': 'copy of rightShelf (4)',
         'comment': '',
         'parentEntId': 10022,
         'pos': Point3(-8.7173, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10028: {'type': 'model',
         'name': 'copy of rightShelf (5)',
         'comment': '',
         'parentEntId': 10022,
         'pos': Point3(-17.416, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfB.bam'},
 10030: {'type': 'model',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10029,
         'pos': Point3(0, 0, 0),
         'hpr': Point3(180, 0, 0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfA.bam'},
 10031: {'type': 'model',
         'name': 'moveWall',
         'comment': '',
         'parentEntId': 10029,
         'pos': Point3(-8.7, 0, 0),
         'hpr': Point3(180, 0, 0),
         'scale': Point3(1, 0.7, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfA.bam'},
 10033: {'type': 'model',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 10032,
         'pos': Point3(0, 0, 0),
         'hpr': Point3(180, 0, 0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfA.bam'},
 10034: {'type': 'model',
         'name': 'copy of <unnamed> (2)',
         'comment': '',
         'parentEntId': 10032,
         'pos': Point3(8.7, 0, 0),
         'hpr': Point3(180, 0, 0),
         'scale': Point3(1, 0.7, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_bookshelfA.bam'},
 10046: {'type': 'model',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10068,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/PartitionA.bam'},
 10047: {'type': 'model',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 10068,
         'pos': Point3(14.75, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/PartitionA.bam'},
 10048: {'type': 'model',
         'name': 'copy of <unnamed> (2)',
         'comment': '',
         'parentEntId': 10068,
         'pos': Point3(-14.75, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/PartitionA.bam'},
 10049: {'type': 'model',
         'name': 'copy of <unnamed> (3)',
         'comment': '',
         'parentEntId': 10068,
         'pos': Point3(-29.5, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/PartitionA.bam'},
 10051: {'type': 'model',
         'name': 'copy of <unnamed> (2)',
         'comment': '',
         'parentEntId': 10069,
         'pos': Point3(-14.75, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/PartitionA.bam'},
 10052: {'type': 'model',
         'name': 'copy of <unnamed> (3)',
         'comment': '',
         'parentEntId': 10069,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/PartitionA.bam'},
 10053: {'type': 'model',
         'name': 'copy of <unnamed> (3)',
         'comment': '',
         'parentEntId': 10069,
         'pos': Point3(14.75, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/PartitionA.bam'},
 10054: {'type': 'model',
         'name': 'copy of <unnamed> (4)',
         'comment': '',
         'parentEntId': 10069,
         'pos': Point3(29.5, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/PartitionA.bam'},
 10010: {'type': 'mover',
         'name': 'shelfMover',
         'comment': '',
         'parentEntId': 10014,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'cycleType': 'loop',
         'entity2Move': 10009,
         'modelPath': 0,
         'moveTarget': 10011,
         'pos0Move': 2.0,
         'pos0Wait': 0.0,
         'pos1Move': 2,
         'pos1Wait': 3.0,
         'startOn': 1,
         'switchId': 0},
 10035: {'type': 'mover',
         'name': 'wallMover',
         'comment': '',
         'parentEntId': 10029,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'cycleType': 'loop',
         'entity2Move': 10031,
         'modelPath': 0,
         'moveTarget': 10036,
         'pos0Move': 2,
         'pos0Wait': 6.0,
         'pos1Move': 2,
         'pos1Wait': 2,
         'startOn': 1,
         'switchId': 0},
 10037: {'type': 'mover',
         'name': 'copy of wallMover',
         'comment': '',
         'parentEntId': 10032,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'cycleType': 'loop',
         'entity2Move': 10034,
         'modelPath': 0,
         'moveTarget': 10038,
         'pos0Move': 2,
         'pos0Wait': 6.0,
         'pos1Move': 2,
         'pos1Wait': 2.0,
         'startOn': 1,
         'switchId': 0},
 10000: {'type': 'nodepath',
         'name': 'center',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10008: {'type': 'nodepath',
         'name': 'maze',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-11.32, 35.7767, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(1.4, 1.4, 1.4)},
 10011: {'type': 'nodepath',
         'name': 'movetarget',
         'comment': '',
         'parentEntId': 10014,
         'pos': Point3(7, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10014: {'type': 'nodepath',
         'name': 'frontDoor',
         'comment': '',
         'parentEntId': 10008,
         'pos': Point3(0, 0.75, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10016: {'type': 'nodepath',
         'name': 'firstInnerWall',
         'comment': '',
         'parentEntId': 10008,
         'pos': Point3(-1.4, 9.5, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10021: {'type': 'nodepath',
         'name': 'rightWall',
         'comment': '',
         'parentEntId': 10008,
         'pos': Point3(28.038, 16.5374, 0),
         'hpr': Point3(90, 0, 0),
         'scale': Vec3(1, 1, 1)},
 10022: {'type': 'nodepath',
         'name': 'leftWall',
         'comment': '',
         'parentEntId': 10008,
         'pos': Point3(-12.3934, 5.78821, 0),
         'hpr': Point3(270, 0, 0),
         'scale': Vec3(1, 1, 1)},
 10029: {'type': 'nodepath',
         'name': 'rearRightWall',
         'comment': '',
         'parentEntId': 10008,
         'pos': Point3(19.8603, 23.5345, 0),
         'hpr': Point3(90, 0, 0),
         'scale': Vec3(1, 1, 1)},
 10032: {'type': 'nodepath',
         'name': 'rearLeftWall',
         'comment': '',
         'parentEntId': 10008,
         'pos': Point3(-5.06744, 23.3692, 0),
         'hpr': Point3(270, 0, 0),
         'scale': Vec3(1, 1, 1)},
 10036: {'type': 'nodepath',
         'name': 'moveTarget',
         'comment': '',
         'parentEntId': 10029,
         'pos': Point3(8.7, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10038: {'type': 'nodepath',
         'name': 'copy of moveTarget',
         'comment': '',
         'parentEntId': 10032,
         'pos': Point3(-8.7, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10039: {'type': 'nodepath',
         'name': 'stompers',
         'comment': '',
         'parentEntId': 10008,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10044: {'type': 'nodepath',
         'name': 'walls',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10045: {'type': 'nodepath',
         'name': 'leftWall',
         'comment': '',
         'parentEntId': 10044,
         'pos': Point3(-40, -2, 0),
         'hpr': Point3(270, 0, 0),
         'scale': Point3(1, 1, 1)},
 10050: {'type': 'nodepath',
         'name': 'rightWall',
         'comment': '',
         'parentEntId': 10044,
         'pos': Point3(40, -2, 0),
         'hpr': Point3(90, 0, 0),
         'scale': Point3(1, 1, 1)},
 10062: {'type': 'nodepath',
         'name': 'cameras',
         'comment': '',
         'parentEntId': 10045,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10063: {'type': 'nodepath',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10062,
         'pos': Point3(5, 6, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10065: {'type': 'nodepath',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 10062,
         'pos': Point3(-10, 6, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10066: {'type': 'nodepath',
         'name': 'copy of <unnamed> (2)',
         'comment': '',
         'parentEntId': 10062,
         'pos': Point3(5, 17, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10067: {'type': 'nodepath',
         'name': 'copy of <unnamed> (3)',
         'comment': '',
         'parentEntId': 10062,
         'pos': Point3(-10, 17, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10068: {'type': 'nodepath',
         'name': 'scaleNode',
         'comment': '',
         'parentEntId': 10045,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1.7, 1, 1)},
 10069: {'type': 'nodepath',
         'name': 'scaleNode',
         'comment': '',
         'parentEntId': 10050,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1.7, 1, 1)},
 10070: {'type': 'nodepath',
         'name': 'cameras',
         'comment': '',
         'parentEntId': 10050,
         'pos': Point3(4, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10073: {'type': 'nodepath',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10070,
         'pos': Point3(5, 6, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10074: {'type': 'nodepath',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 10070,
         'pos': Point3(-10, 6, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10075: {'type': 'nodepath',
         'name': 'copy of <unnamed> (2)',
         'comment': '',
         'parentEntId': 10070,
         'pos': Point3(5, 17, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10076: {'type': 'nodepath',
         'name': 'copy of <unnamed> (3)',
         'comment': '',
         'parentEntId': 10070,
         'pos': Point3(-10, 17, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10056: {'type': 'securityCamera',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10062,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'accel': 1,
         'damPow': 8,
         'hideModel': 0,
         'maxVel': 5,
         'modelPath': 0,
         'projector': Point3(0, 0, 28),
         'radius': 5,
         'switchId': 0,
         'trackTarget1': 10063,
         'trackTarget2': 10065,
         'trackTarget3': 10066},
 10057: {'type': 'securityCamera',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10062,
         'pos': Point3(-10, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'accel': 1,
         'damPow': 8,
         'hideModel': 0,
         'maxVel': 5,
         'modelPath': 0,
         'projector': Point3(0, 0, 28),
         'radius': 5,
         'switchId': 0,
         'trackTarget1': 10065,
         'trackTarget2': 10066,
         'trackTarget3': 10067},
 10071: {'type': 'securityCamera',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10070,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'accel': 1,
         'damPow': 8,
         'hideModel': 0,
         'maxVel': 5,
         'modelPath': 0,
         'projector': Point3(0, 0, 28),
         'radius': 5,
         'switchId': 0,
         'trackTarget1': 10073,
         'trackTarget2': 10074,
         'trackTarget3': 10075},
 10072: {'type': 'securityCamera',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10070,
         'pos': Point3(-10, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'accel': 1,
         'damPow': 8,
         'hideModel': 0,
         'maxVel': 5,
         'modelPath': 0,
         'projector': Point3(0, 0, 28),
         'radius': 5,
         'switchId': 0,
         'trackTarget1': 10074,
         'trackTarget2': 10075,
         'trackTarget3': 10076},
 10040: {'type': 'stomper',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10039,
         'pos': Point3(0, 5.05514, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(2.5, 2.5, 2.5),
         'animateShadow': 1,
         'cogStyle': 1,
         'crushCellId': None,
         'damage': 10,
         'headScale': Vec3(1, 1, 1),
         'modelPath': 0,
         'motion': 3,
         'period': 2.0,
         'phaseShift': 0.0,
         'range': 3.0,
         'removeCamBarrierCollisions': 0,
         'removeHeadFloor': 0,
         'shaftScale': Point3(1, 12, 1),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 10041: {'type': 'stomper',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 10039,
         'pos': Point3(20, 5.06, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(2.5, 2.5, 2.5),
         'animateShadow': 1,
         'cogStyle': 1,
         'crushCellId': None,
         'damage': 10,
         'headScale': Vec3(1, 1, 1),
         'modelPath': 0,
         'motion': 3,
         'period': 2.0,
         'phaseShift': 0.0,
         'range': 3.0,
         'removeCamBarrierCollisions': 0,
         'removeHeadFloor': 0,
         'shaftScale': Point3(1, 12, 1),
         'soundLen': 0,
         'soundOn': 0,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 10042: {'type': 'stomper',
         'name': 'copy of <unnamed> (2)',
         'comment': '',
         'parentEntId': 10039,
         'pos': Point3(23.7219, 13.3088, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(2.5, 2.5, 2.5),
         'animateShadow': 1,
         'cogStyle': 1,
         'crushCellId': None,
         'damage': 10,
         'headScale': Vec3(1, 1, 1),
         'modelPath': 0,
         'motion': 3,
         'period': 2.0,
         'phaseShift': 0.0,
         'range': 3.0,
         'removeCamBarrierCollisions': 0,
         'removeHeadFloor': 0,
         'shaftScale': Point3(1, 8, 1),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 0,
         'zOffset': 0},
 10043: {'type': 'stomper',
         'name': 'copy of <unnamed> (3)',
         'comment': '',
         'parentEntId': 10039,
         'pos': Point3(-8.59782, 13.3088, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(2.5, 2.5, 2.5),
         'animateShadow': 1,
         'cogStyle': 1,
         'crushCellId': None,
         'damage': 10,
         'headScale': Vec3(1, 1, 1),
         'modelPath': 0,
         'motion': 3,
         'period': 2.0,
         'phaseShift': 0.0,
         'range': 3.0,
         'removeCamBarrierCollisions': 0,
         'removeHeadFloor': 0,
         'shaftScale': Point3(1, 8, 1),
         'soundLen': 0,
         'soundOn': 0,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 0,
         'zOffset': 0}}
Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0]}
