from toontown.coghq.SpecImports import *
GlobalEntities = {1000: {'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500,
        'modelFilename': 'phase_11/models/lawbotHQ/LB_Zone04a',
        'wantDoors': 1},
 1001: {'type': 'editMgr',
        'name': 'EditMgr',
        'parentEntId': 0,
        'insertEntity': None,
        'removeEntity': None,
        'requestNewEntity': None,
        'requestSave': None},
 0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
 10005: {'type': 'attribModifier',
         'name': 'stomperPeriod',
         'comment': '',
         'parentEntId': 10046,
         'attribName': 'period',
         'recursive': 1,
         'typeName': 'stomper',
         'value': '2.2'},
 10015: {'type': 'attribModifier',
         'name': 'stomperShaftScale',
         'comment': '',
         'parentEntId': 10046,
         'attribName': 'shaftScale',
         'recursive': 1,
         'typeName': 'stomper',
         'value': 'Vec3(1,5,1)'},
 10067: {'type': 'attribModifier',
         'name': 'stomperDamage',
         'comment': '',
         'parentEntId': 10000,
         'attribName': 'damage',
         'recursive': 1,
         'typeName': 'stomper',
         'value': '8'},
 10130: {'type': 'attribModifier',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10153,
         'attribName': 'modelPath',
         'recursive': 1,
         'typeName': 'model',
         'value': "'phase_10/models/cogHQ/CBMetalCrate2.bam'"},
 10145: {'type': 'attribModifier',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 10007,
         'attribName': 'modelPath',
         'recursive': 1,
         'typeName': 'model',
         'value': "'phase_10/models/cogHQ/CBMetalCrate2.bam'"},
 10173: {'type': 'attribModifier',
         'name': 'copy of stomperShaftScale',
         'comment': '',
         'parentEntId': 10154,
         'attribName': 'shaftScale',
         'recursive': 1,
         'typeName': 'stomper',
         'value': 'Vec3(1,5,1)'},
 10169: {'type': 'gagBarrel',
         'name': 'gag',
         'comment': '',
         'parentEntId': 10170,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(1.0, 0.0, 0.0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 6},
 10171: {'type': 'gagBarrel',
         'name': 'gagLeft',
         'comment': '',
         'parentEntId': 10170,
         'pos': Point3(-3.0, 0.0, 0.0),
         'hpr': Vec3(-6.0, 0.0, 0.0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 6},
 10172: {'type': 'gagBarrel',
         'name': 'gagRight',
         'comment': '',
         'parentEntId': 10170,
         'pos': Point3(3.0, 0.0, 0.0),
         'hpr': Vec3(9.0, 0.0, 0.0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 6},
 10177: {'type': 'healBarrel',
         'name': 'healLeft',
         'comment': '',
         'parentEntId': 10170,
         'pos': Point3(-1.05319225788, 0.0, 4.12134313583),
         'hpr': Vec3(20.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 6},
 10178: {'type': 'healBarrel',
         'name': 'healRight',
         'comment': '',
         'parentEntId': 10170,
         'pos': Point3(2.16605138779, 0.0, 4.12134313583),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 6},
 10181: {'type': 'healBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-2.92873573303, 110.585220337, 5.00378036499),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 10001: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10004,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10002: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10004,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10003: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10004,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10008: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10006,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10009: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10006,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10011: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10010,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10012: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10010,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10013: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10010,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10014: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10022,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10024: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10020,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10025: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10020,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10027: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10021,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10028: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10021,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10029: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10022,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10030: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10022,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10036: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10033,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10037: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10033,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10038: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10033,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10039: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10034,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10040: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10034,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10041: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10034,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10042: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10035,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10043: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10035,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10048: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10044,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10049: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10044,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10050: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10045,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10051: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10045,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10052: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10047,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10053: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10047,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10076: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10075,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10077: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10075,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10078: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10075,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10079: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10047,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10084: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10081,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10085: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10081,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10086: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10081,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10087: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10082,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10088: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10082,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10089: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10082,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10090: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10083,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10091: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10083,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10102: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10072,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10108: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10105,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10109: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10105,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10110: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10072,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10111: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10106,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10112: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10106,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10113: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10072,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10114: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10107,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10115: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10107,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10116: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10107,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10121: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10118,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10122: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10118,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10123: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10118,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10124: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10119,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10125: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10119,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10126: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10119,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10127: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10120,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10128: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10120,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10129: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10073,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10131: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10073,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10132: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10074,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10133: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10074,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10134: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10074,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10139: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10136,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10140: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10136,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10141: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10136,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10143: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10137,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10146: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10137,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10147: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10138,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10148: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10138,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10149: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10144,
         'pos': Point3(-6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10150: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10144,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10151: {'type': 'model',
         'name': 'right',
         'comment': '',
         'parentEntId': 10144,
         'pos': Point3(6.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10152: {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 10138,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cogHQ/CBMetalCrate2.bam'},
 10158: {'type': 'model',
         'name': 'left',
         'comment': '',
         'parentEntId': 10157,
         'pos': Point3(-11.0, 0.0, 0.0),
         'hpr': Point3(90.0, 0.0, 0.0),
         'scale': Vec3(1.34000003338, 1.34000003338, 1.34000003338),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_10/models/cashbotHQ/shelf_A1.bam'},
 10000: {'type': 'nodepath',
         'name': 'crateField',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, -51.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 1.0)},
 10004: {'type': 'nodepath',
         'name': 'row0',
         'comment': '',
         'parentEntId': 10018,
         'pos': Point3(0.0, -6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10006: {'type': 'nodepath',
         'name': 'row1',
         'comment': '',
         'parentEntId': 10018,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10007: {'type': 'nodepath',
         'name': 'crates',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 0.800000011921)},
 10010: {'type': 'nodepath',
         'name': 'row2',
         'comment': '',
         'parentEntId': 10018,
         'pos': Point3(0.0, 6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10017: {'type': 'nodepath',
         'name': 'wall5',
         'comment': '',
         'parentEntId': 10063,
         'pos': Point3(0.0, 90.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 1.0)},
 10018: {'type': 'nodepath',
         'name': 'crateSquare0',
         'comment': 'Y=N*18',
         'parentEntId': 10007,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10019: {'type': 'nodepath',
         'name': 'crateSquare1',
         'comment': 'Y=N*18',
         'parentEntId': 10007,
         'pos': Point3(0.0, 18.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10020: {'type': 'nodepath',
         'name': 'row2',
         'comment': '',
         'parentEntId': 10019,
         'pos': Point3(0.0, 6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10021: {'type': 'nodepath',
         'name': 'row0',
         'comment': '',
         'parentEntId': 10019,
         'pos': Point3(0.0, -6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10022: {'type': 'nodepath',
         'name': 'row1',
         'comment': '',
         'parentEntId': 10019,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10031: {'type': 'nodepath',
         'name': 'crateSquare3',
         'comment': 'Y=N*18',
         'parentEntId': 10007,
         'pos': Point3(0.0, 54.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10032: {'type': 'nodepath',
         'name': 'crateSquare2',
         'comment': 'Y=N*18',
         'parentEntId': 10007,
         'pos': Point3(0.0, 36.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10033: {'type': 'nodepath',
         'name': 'row2',
         'comment': '',
         'parentEntId': 10032,
         'pos': Point3(0.0, 6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10034: {'type': 'nodepath',
         'name': 'row0',
         'comment': '',
         'parentEntId': 10032,
         'pos': Point3(0.0, -6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10035: {'type': 'nodepath',
         'name': 'row1',
         'comment': '',
         'parentEntId': 10032,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10044: {'type': 'nodepath',
         'name': 'row2',
         'comment': '',
         'parentEntId': 10031,
         'pos': Point3(0.0, 6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10045: {'type': 'nodepath',
         'name': 'row0',
         'comment': '',
         'parentEntId': 10031,
         'pos': Point3(0.0, -6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10046: {'type': 'nodepath',
         'name': 'stompers',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(-1.0, 0.0, 4.40000009537),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10047: {'type': 'nodepath',
         'name': 'row1',
         'comment': '',
         'parentEntId': 10031,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10059: {'type': 'nodepath',
         'name': 'wall6',
         'comment': '',
         'parentEntId': 10063,
         'pos': Point3(0.0, 108.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 1.0)},
 10062: {'type': 'nodepath',
         'name': 'wall7',
         'comment': '',
         'parentEntId': 10063,
         'pos': Point3(0.0, 124.5, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.39999997616, 1.0)},
 10063: {'type': 'nodepath',
         'name': 'walls',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(0.0, -0.019999999553, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10065: {'type': 'nodepath',
         'name': 'wall0',
         'comment': '',
         'parentEntId': 10063,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 1.0)},
 10070: {'type': 'nodepath',
         'name': 'leftBranch',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(-17.8978881836, 72.0, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10071: {'type': 'nodepath',
         'name': 'crateSquare0',
         'comment': 'Y=N*18',
         'parentEntId': 10153,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10072: {'type': 'nodepath',
         'name': 'row2',
         'comment': '',
         'parentEntId': 10071,
         'pos': Point3(0.0, 6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10073: {'type': 'nodepath',
         'name': 'row0',
         'comment': '',
         'parentEntId': 10071,
         'pos': Point3(0.0, -6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10074: {'type': 'nodepath',
         'name': 'row1',
         'comment': '',
         'parentEntId': 10071,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10075: {'type': 'nodepath',
         'name': 'frontCrateRow',
         'comment': '',
         'parentEntId': 10007,
         'pos': Point3(0.0, -12.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(0.844285488129, 1.0, 1.0)},
 10080: {'type': 'nodepath',
         'name': 'crateSquare4',
         'comment': 'Y=N*18',
         'parentEntId': 10007,
         'pos': Point3(0.0, 72.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10081: {'type': 'nodepath',
         'name': 'row2',
         'comment': '',
         'parentEntId': 10080,
         'pos': Point3(0.0, 6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10082: {'type': 'nodepath',
         'name': 'row0',
         'comment': '',
         'parentEntId': 10080,
         'pos': Point3(0.0, -6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10083: {'type': 'nodepath',
         'name': 'row1',
         'comment': '',
         'parentEntId': 10080,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10092: {'type': 'nodepath',
         'name': 'wall1',
         'comment': '',
         'parentEntId': 10063,
         'pos': Point3(0.0, 18.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 1.0)},
 10095: {'type': 'nodepath',
         'name': 'wall2',
         'comment': '',
         'parentEntId': 10063,
         'pos': Point3(0.0, 36.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 1.0)},
 10098: {'type': 'nodepath',
         'name': 'wall3',
         'comment': '',
         'parentEntId': 10063,
         'pos': Point3(0.0, 54.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 1.0)},
 10101: {'type': 'nodepath',
         'name': 'wall4',
         'comment': '',
         'parentEntId': 10063,
         'pos': Point3(0.0, 72.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 1.0)},
 10104: {'type': 'nodepath',
         'name': 'crateSquare5',
         'comment': 'Y=N*18',
         'parentEntId': 10007,
         'pos': Point3(0.0, 90.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10105: {'type': 'nodepath',
         'name': 'row2',
         'comment': '',
         'parentEntId': 10104,
         'pos': Point3(0.0, 6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10106: {'type': 'nodepath',
         'name': 'row0',
         'comment': '',
         'parentEntId': 10104,
         'pos': Point3(0.0, -6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10107: {'type': 'nodepath',
         'name': 'row1',
         'comment': '',
         'parentEntId': 10104,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10117: {'type': 'nodepath',
         'name': 'crateSquare6',
         'comment': 'Y=N*18',
         'parentEntId': 10007,
         'pos': Point3(0.0, 108.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10118: {'type': 'nodepath',
         'name': 'row2',
         'comment': '',
         'parentEntId': 10117,
         'pos': Point3(0.0, 6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10119: {'type': 'nodepath',
         'name': 'row0',
         'comment': '',
         'parentEntId': 10117,
         'pos': Point3(0.0, -6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10120: {'type': 'nodepath',
         'name': 'row1',
         'comment': '',
         'parentEntId': 10117,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10135: {'type': 'nodepath',
         'name': 'crateSquare1',
         'comment': 'Y=N*18',
         'parentEntId': 10153,
         'pos': Point3(0.0, 18.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10136: {'type': 'nodepath',
         'name': 'row2',
         'comment': '',
         'parentEntId': 10135,
         'pos': Point3(0.0, 6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10137: {'type': 'nodepath',
         'name': 'row0',
         'comment': '',
         'parentEntId': 10135,
         'pos': Point3(0.0, -6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10138: {'type': 'nodepath',
         'name': 'row1',
         'comment': '',
         'parentEntId': 10135,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10142: {'type': 'nodepath',
         'name': 'crateSquare7',
         'comment': 'Y=N*18',
         'parentEntId': 10007,
         'pos': Point3(0.0, 126.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10144: {'type': 'nodepath',
         'name': 'row0',
         'comment': '',
         'parentEntId': 10142,
         'pos': Point3(0.0, -6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10153: {'type': 'nodepath',
         'name': 'crates',
         'comment': '',
         'parentEntId': 10070,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 0.800000011921)},
 10154: {'type': 'nodepath',
         'name': 'stompers',
         'comment': '',
         'parentEntId': 10070,
         'pos': Point3(-1.0, 0.0, 4.40000009537),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10156: {'type': 'nodepath',
         'name': 'walls',
         'comment': '',
         'parentEntId': 10070,
         'pos': Point3(0.0, 6.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10157: {'type': 'nodepath',
         'name': 'wall0',
         'comment': '',
         'parentEntId': 10156,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 1.0)},
 10160: {'type': 'nodepath',
         'name': 'wall1',
         'comment': '',
         'parentEntId': 10156,
         'pos': Point3(0.0, 18.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 1.0)},
 10163: {'type': 'nodepath',
         'name': 'wall2',
         'comment': '',
         'parentEntId': 10156,
         'pos': Point3(0.0, 36.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Point3(1.0, 1.0, 1.0)},
 10168: {'type': 'nodepath',
         'name': 'safeArea',
         'comment': '',
         'parentEntId': 10070,
         'pos': Point3(0.0, 40.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10170: {'type': 'nodepath',
         'name': 'barrels',
         'comment': '',
         'parentEntId': 10168,
         'pos': Point3(0.0, 9.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10016: {'type': 'stomper',
         'name': 'stomper6',
         'comment': 'Y=N*18',
         'parentEntId': 10046,
         'pos': Point3(1.0, 108.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'animateShadow': 1,
         'crushCellId': None,
         'damage': 8,
         'headScale': Point3(9.0, 9.0, 9.0),
         'modelPath': 0,
         'motion': 2,
         'period': 2.2,
         'phaseShift': 0.0,
         'range': 13.0,
         'removeCamBarrierCollisions': 1,
         'removeHeadFloor': 1,
         'shaftScale': Vec3(1.0, 5.0, 1.0),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 0,
         'zOffset': 0},
 10054: {'type': 'stomper',
         'name': 'stomper1',
         'comment': '',
         'parentEntId': 10046,
         'pos': Point3(1.0, 18.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'animateShadow': 1,
         'crushCellId': None,
         'damage': 8,
         'headScale': Point3(9.0, 9.0, 9.0),
         'modelPath': 0,
         'motion': 2,
         'period': 2.2,
         'phaseShift': 0.0,
         'range': 13.0,
         'removeCamBarrierCollisions': 1,
         'removeHeadFloor': 1,
         'shaftScale': Vec3(1.0, 5.0, 1.0),
         'soundLen': 0,
         'soundOn': 0,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 0,
         'zOffset': 0},
 10055: {'type': 'stomper',
         'name': 'stomper0',
         'comment': 'Y=N*18',
         'parentEntId': 10046,
         'pos': Point3(1.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'animateShadow': 1,
         'crushCellId': None,
         'damage': 8,
         'headScale': Point3(9.0, 9.0, 9.0),
         'modelPath': 0,
         'motion': 2,
         'period': 2.2,
         'phaseShift': 0.0,
         'range': 13.0,
         'removeCamBarrierCollisions': 1,
         'removeHeadFloor': 1,
         'shaftScale': Vec3(1.0, 5.0, 1.0),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 0,
         'zOffset': 0},
 10056: {'type': 'stomper',
         'name': 'stomper2',
         'comment': '',
         'parentEntId': 10046,
         'pos': Point3(1.0, 36.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'animateShadow': 1,
         'crushCellId': None,
         'damage': 8,
         'headScale': Point3(9.0, 9.0, 9.0),
         'modelPath': 0,
         'motion': 2,
         'period': 2.2,
         'phaseShift': 0.0,
         'range': 13.0,
         'removeCamBarrierCollisions': 1,
         'removeHeadFloor': 1,
         'shaftScale': Vec3(1.0, 5.0, 1.0),
         'soundLen': 0,
         'soundOn': 0,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 0,
         'zOffset': 0},
 10057: {'type': 'stomper',
         'name': 'stomper3',
         'comment': '',
         'parentEntId': 10046,
         'pos': Point3(1.0, 54.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'animateShadow': 1,
         'crushCellId': None,
         'damage': 8,
         'headScale': Point3(9.0, 9.0, 9.0),
         'modelPath': 0,
         'motion': 2,
         'period': 2.2,
         'phaseShift': 0.0,
         'range': 13.0,
         'removeCamBarrierCollisions': 1,
         'removeHeadFloor': 1,
         'shaftScale': Vec3(1.0, 5.0, 1.0),
         'soundLen': 0,
         'soundOn': 0,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 0,
         'zOffset': 0},
 10058: {'type': 'stomper',
         'name': 'stomper4',
         'comment': '',
         'parentEntId': 10046,
         'pos': Point3(1.0, 72.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'animateShadow': 1,
         'crushCellId': None,
         'damage': 8,
         'headScale': Point3(9.0, 9.0, 9.0),
         'modelPath': 0,
         'motion': 2,
         'period': 2.2,
         'phaseShift': 0.0,
         'range': 13.0,
         'removeCamBarrierCollisions': 1,
         'removeHeadFloor': 1,
         'shaftScale': Vec3(1.0, 5.0, 1.0),
         'soundLen': 0,
         'soundOn': 0,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 0,
         'zOffset': 0},
 10155: {'type': 'stomper',
         'name': 'stomper5',
         'comment': '',
         'parentEntId': 10046,
         'pos': Point3(1.0, 90.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'animateShadow': 1,
         'crushCellId': None,
         'damage': 8,
         'headScale': Point3(9.0, 9.0, 9.0),
         'modelPath': 0,
         'motion': 2,
         'period': 2.2,
         'phaseShift': 0.0,
         'range': 13.0,
         'removeCamBarrierCollisions': 1,
         'removeHeadFloor': 1,
         'shaftScale': Vec3(1.0, 5.0, 1.0),
         'soundLen': 0,
         'soundOn': 0,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 0,
         'zOffset': 0},
 10166: {'type': 'stomper',
         'name': 'stomper0',
         'comment': 'Y=N*18',
         'parentEntId': 10154,
         'pos': Point3(1.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'animateShadow': 1,
         'crushCellId': None,
         'damage': 8,
         'headScale': Point3(9.0, 9.0, 9.0),
         'modelPath': 0,
         'motion': 2,
         'period': 2.2,
         'phaseShift': 0.0,
         'range': 13.0,
         'removeCamBarrierCollisions': 1,
         'removeHeadFloor': 1,
         'shaftScale': Vec3(1.0, 5.0, 1.0),
         'soundLen': 0,
         'soundOn': 0,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 0,
         'zOffset': 0},
 10167: {'type': 'stomper',
         'name': 'stomper1',
         'comment': 'Y=N*18',
         'parentEntId': 10154,
         'pos': Point3(1.0, 18.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'animateShadow': 1,
         'crushCellId': None,
         'damage': 8,
         'headScale': Point3(9.0, 9.0, 9.0),
         'modelPath': 0,
         'motion': 2,
         'period': 2.2,
         'phaseShift': 0.0,
         'range': 13.0,
         'removeCamBarrierCollisions': 1,
         'removeHeadFloor': 1,
         'shaftScale': Vec3(1.0, 5.0, 1.0),
         'soundLen': 0,
         'soundOn': 0,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 0,
         'zOffset': 0}}
Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0]}
