from .TTSCToontaskMenu import TTSCToontaskMenu
from .TTSCFactoryMenu import TTSCFactoryMenu
from .TTSCCogMenu import TTSCCogMenu
if hasattr(base, 'wantPets') and base.wantPets:
    from .TTSCPetTrickMenu import TTSCPetTrickMenu
from .TTSCPromotionalMenu import TTSCPromotionalMenu
from .TTSCToontaskTerminal import TTSCToontaskTerminal
from .TTSCResistanceMenu import TTSCResistanceMenu
from .TTSCResistanceTerminal import TTSCResistanceTerminal
from .TTSCKartRacingMenu import TTSCKartRacingMenu
from .TTSCGolfMenu import TTSCGolfMenu
from .TTSCBoardingMenu import TTSCBoardingMenu
from .TTSCSingingMenu import TTSCSingingMenu
from .TTSCAprilToonsMenu import TTSCAprilToonsMenu
from .TTSCSillyPhaseOneMenu import TTSCSillyPhaseOneMenu
from .TTSCSillyPhaseTwoMenu import TTSCSillyPhaseTwoMenu
from .TTSCSillyPhaseThreeMenu import TTSCSillyPhaseThreeMenu
from .TTSCSillyPhaseFourMenu import TTSCSillyPhaseFourMenu
from .TTSCSillyPhaseFiveMenu import TTSCSillyPhaseFiveMenu
from .TTSCVictoryPartiesMenu import TTSCVictoryPartiesMenu
from .TTSCSellbotNerfMenu import TTSCSellbotNerfMenu
from .TTSCJellybeanJamMenu import TTSCJellybeanJamMenu
from .TTSCHalloweenMenu import TTSCHalloweenMenu
from .TTSCWinterMenu import TTSCWinterMenu
from .TTSCSellbotInvasionMenu import TTSCSellbotInvasionMenu
from .TTSCSellbotFieldOfficeMenu import TTSCSellbotFieldOfficeMenu
from .TTSCIdesOfMarchMenu import TTSCIdesOfMarchMenu
