want-render2dp 1
text-encoding utf8
direct-wtext 0
text-never-break-before ,.-:?!;
ime-aware 1
ime-hide 1
textures-power-2 down
paranoid-clock 1
collect-tcp 1
collect-tcp-interval 0.2
server-version sv1.0.47.38
server-version-suffix
model-path resources
dc-file etc/toon.dc
dc-file etc/otp.dc
window-title Toontown
verify-ssl 0
ssl-cipher-list DEFAULT
chan-config-sanity-check #f
require-window 0
language english
icon-filename phase_3/models/gui/toontown.ico
dx-management 1
tt-specific-login 1
decompressor-buffer-size 32768
extractor-buffer-size 32768
patcher-buffer-size 512000
downloader-timeout 15
downloader-timeout-retries 4
downloader-disk-write-frequency 4
downloader-byte-rate 125000
downloader-frequency 0.1
http-connect-timeout 20
http-timeout 30
contents-xml-dl-attempts 2
load-display pandagl
aux-display pandagl
aux-display pandadx9
aux-display tinydisplay
depth-bits 24
win-size 800 600
fullscreen #t
compress-channels #f
display-lists 0
early-random-seed 1
ssl-cipher-list DEFAULT
respect-prev-transform 1
default-directnotify-level info
notify-level-collide warning
notify-level-chan warning
notify-level-gobj warning
notify-level-loader warning
notify-timestamp #t
default-model-extension .bam
decompressor-step-time 0.5
extractor-step-time 0.5
required-login playToken
server-failover 80 443
want-fog #t
dx-use-rangebased-fog #t
aspect-ratio 1.333333
on-screen-debug-font ImpressBT.ttf
temp-hpr-fix 1
vertex-buffers 0
dx-broken-max-index 1
vfs-case-sensitive 0
inactivity-timeout 180
merge-lod-bundles 0
early-event-sphere 1
accept-clock-skew 1
extra-ssl-handshake-time 20.0
prefer-parasite-buffer 0
audio-library-name miles_audio
cursor-filename phase_3/models/gui/toonmono.cur
audio-loader mp3
audio-loader midi
audio-loader wav
audio-software-midi #t
audio-sfx-active #t
audio-music-active #t
audio-master-sfx-volume 1
audio-master-music-volume 1
server-type prod
want-dev 0
schellgames-dev 0
text-minfilter linear_mipmap_linear
gc-save-all 0

# TEMP
fake-playtoken dev
