direct-wtext 0
ime-aware 1
ime-hide 1
collect-tcp 1
server-version sv1.0.47.38
model-path resources
dc-file etc/toon.dc
dc-file etc/otp.dc
window-title Toontown
verify-ssl 0
require-window 0
icon-filename phase_3/models/gui/toontown.ico
dx-management 1
tt-specific-login 1
patcher-buffer-size 512000
downloader-timeout-retries 4
downloader-byte-rate 125000
downloader-frequency 0.1
http-connect-timeout 20
http-timeout 30
load-display pandagl
aux-display pandagl
aux-display pandadx9
aux-display tinydisplay
depth-bits 24
early-random-seed 1
respect-prev-transform 1
default-directnotify-level info
notify-level-collide warning
notify-level-chan warning
notify-level-gobj warning
notify-level-loader warning
notify-timestamp #t
notify-integrate #f
console-output 1
default-model-extension .bam
decompressor-step-time 0.5
extractor-step-time 0.5
required-login playToken
server-failover 80 443
dx-use-rangebased-fog #t
aspect-ratio 1.333333
on-screen-debug-font ImpressBT.ttf
temp-hpr-fix 1
vertex-buffers 0
dx-broken-max-index 1
vfs-case-sensitive 0
inactivity-timeout 180
merge-lod-bundles 0
early-event-sphere 1
accept-clock-skew 1
extra-ssl-handshake-time 20.0
audio-library-name p3openal_audio
cursor-filename phase_3/models/gui/toonmono.cur
audio-sfx-active #t
audio-music-active #t
want-dev 0
schellgames-dev 0
text-minfilter linear_mipmap_linear
gc-save-all 0
